name: Keep draw.io export synchronized
on:
  push:
    branches:
      master
    paths:
      "flink/*.drawio"
concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Export drawio files to asciidoctor and png files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          action-mode: all

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1
        if: github.ref == 'refs/heads/master'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          default_author: github_actor
          commit_message: "docs: sync draw.io exported files"
        if: github.ref == 'refs/heads/master'
